# Generated by Django 4.2.20 on 2025-04-19 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servidor',
            options={},
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='solicitado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocolos.aluno'),
        ),
    ]
