# Generated by Django 4.2.20 on 2025-08-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("protocolos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="telefone",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
