# Generated by Django 4.2.23 on 2025-09-13 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['ordem'], 'verbose_name_plural': 'Status'},
        ),
        migrations.AddField(
            model_name='aluno',
            name='campus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='protocolos.campus'),
        ),
        migrations.AddField(
            model_name='servidor',
            name='campus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='protocolos.campus'),
        ),
    ]
