# Generated by Django 4.2.20 on 2025-07-31 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("protocolos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aluno",
            name="email",
        ),
        migrations.RemoveField(
            model_name="servidor",
            name="email",
        ),
        migrations.AlterField(
            model_name="aluno",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aluno",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="servidor",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="servidor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
