# Generated by Django 4.2.5 on 2025-04-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0003_alter_aluno_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposolicitacao',
            name='descricao',
            field=models.CharField(max_length=100, unique=True, verbose_name='descrição'),
        ),
    ]
