# Generated by Django 4.2.20 on 2025-06-26 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("protocolos", "0004_alter_tiposolicitacao_descricao"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campus",
            options={"ordering": ["nome"], "verbose_name_plural": "Campi"},
        ),
        migrations.AlterModelOptions(
            name="servidor",
            options={"ordering": ["nome"], "verbose_name_plural": "Servidores"},
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="solicitado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
